name: # {your name}-test or some other name that describes the workflow

on:
  # when should this run ðŸ¤”?

jobs:
  build:

    runs-on: ubuntu-latest # Linux FTW!

    steps:
      - uses: actions/checkout@v4
      ###################
      # EXAMPLE STEP
      ###################
      # - name: name
      #   uses: (external action)
      #
      #   - OR -
      #
      # - name: name
      #   run: (command)

      # How many steps do you need and what should they be?
      # What's the best way to split them up to be efficient?
